# Generated by Django 3.2 on 2021-05-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='email_token'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='email_verification_token'),
        ),
    ]
